apiVersion: v1
kind: Service
metadata:
  labels:
    app: ingress-nginx-metrics
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "10254"
  name: ingress-nginx-metrics
  namespace: ingress-nginx
spec:
  ports:
    - name: prometheus
      port: 10254
      targetPort: prometheus
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
  type: ClusterIP
